name: Test Suite

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test
        env:
          CI: true
